<?php

function clock_angle_menu() {
  $items = array();
  $items['clock_angle'] = array(
    'title' => 'Clock Angle',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('clock_angle_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['clock_angle_success_page'] = array(
    'title' => 'Success!',
    'page callback' => 'clock_angle_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function clock_angle_form() {
  $form['time'] = array(
    '#title' => 'Time',
    '#type' => 'textfield',
    '#description' => t('Enter the time. (Example: 12:00)'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Go',
  );
  return $form;
}

function clock_angle_form_submit($form, &$form_state) {
  $time = explode(':', $form_state['values']['time']);
  $hours = intval($time[0]);
  $minutes = intval($time[1]);
  $hours_deg = ((60 * $hours) + $minutes) / 2;
  // $hours_deg = ($hour * 30) + (($minutes/60) * 30);
  $minutes_deg = 6 * $minutes;
  $clock_angle = abs($hours_deg - $minutes_deg);
  if($clock_angle > 180) {
    $_SESSION['clock_angle_output'] = (360 - $clock_angle);
  } else {
    $_SESSION['clock_angle_output'] = $clock_angle;
  }
  $form_state['redirect'] = 'clock_angle_success_page';
}

function clock_angle_success() {
  return '<p>' . $_SESSION['clock_angle_output'] . '</p>';
}
