<?php

function state_poll_menu() {
  $items = array();
  $items['state_poll'] = array(
    'title' => 'State Poll',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('state_poll_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['state_poll_success_page'] = array(
    'title' => 'Success! Thank you for your state!',
    'page callback' => 'state_poll_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function state_poll_form() {
  $form['state'] = array(
    '#title' => 'State',
    '#type' => 'textfield',
    '#description' => t('Enter your state'),
    '#element_validate' => array('element_validate_state'),
    '#required' => TRUE,
  );

  $form['flavor'] = array(
    '#title' => 'Flavor',
    '#type' => 'textfield',
    '#description' => t('Please enter your favorite flavor of ice cream'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Go',
  );
  return $form;
}

function element_validate_state($element) {

  $states = array('Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
  'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
  'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
  'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
  'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey',
  'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma',
  'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
  'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia',
  'Wisconsin', 'Wyoming', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA',
  'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN',
  'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK',
  'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY');

  $lower_case_states = array();
  foreach ($states as $state) {
    array_push($lower_case_states, strtolower($state));
  }
  $user_input = strtolower($element['#value']);

  if (!in_array($user_input, $lower_case_states)) {
    form_error($element, t('That\'s not a state we recognize.'));
  }
}

function state_poll_form_submit($form, &$form_state) {
  $state = $form_state['values']['state'];
  $flavor = $form_state['values']['flavor'];

  $_SESSION['poll_result'] = '<p>You chose ' . $flavor . ' and are from ' . $state . '.</p>';
  $form_state['redirect'] = 'state_poll_success_page';
}

function state_poll_success() {
  return $_SESSION['poll_result'];
}
