<?php

function title_case_menu() {
  $items = array();
  $items['title_case'] = array(
    'title' => 'Title Case',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('title_case_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['title_case_success_page'] = array(
    'title' => 'Success',
    'page callback' => 'title_case_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}


function title_case_form() {
  $form['title_input'] = array(
    '#title' => 'Title',
    '#type' => 'textfield',
    '#description' => t('Please enter a title'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Go',
  );

  return $form;
}

function title_case_form_submit($form, &$form_state) {
  $user_input = $form_state['values']['title_input'];
  $user_input = strtolower($user_input);
  $titlecased_output = ucwords($user_input, " ");

  $_SESSION['title_cased_output'] = $titlecased_output;
  $form_state['redirect'] = 'title_case_success_page';
}

function title_case_success() {
  $output = '<p>' . $_SESSION['title_cased_output'] . '</p>';
  return $output;
}
