<?php

function rock_paper_scissors_menu() {
  $items['rock_paper_scissors'] = array(
    'title' => 'Rock Paper Scissors',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rock_paper_scissors_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['rock_paper_scissors_player_two_page'] = array(
    'title' => 'Player Two\'s selection',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rock_paper_scissors_player_two_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['rock_paper_scissors_success_page'] = array(
    'title' => 'Success',
    'page callback' => 'rock_paper_scissors_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function rock_paper_scissors_form() {
  $form['player_one'] = array(
    '#title' => 'Player one',
    '#type' => 'textfield',
    '#description' => 'Player one',
    '#element_validate' => array('element_validate_rps'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Go',
  );

  return $form;
}

function rock_paper_scissors_form_submit($form, &$form_state) {
  $_SESSION['player_one'] = strtolower($form_state['values']['player_one']);
  $form_state['redirect'] = 'rock_paper_scissors_player_two_page';
}

function rock_paper_scissors_player_two_form() {
  $form['player_two'] = array(
    '#title' => 'Player two',
    '#type' => 'textfield',
    '#description' => 'Player two',
    '#element_validate' => array('element_validate_rps'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Go',
  );

  return $form;
}

function rock_paper_scissors_player_two_form_submit($form, &$form_state) {
  $_SESSION['player_two'] = strtolower($form_state['values']['player_two']);
  $form_state['redirect'] = 'rock_paper_scissors_success_page';
}

function rock_paper_scissors_success() {
  $one = $_SESSION['player_one'];
  $two = $_SESSION['player_two'];

  $outcome = array(
    'rock' => array(
      'rock' => 'It\'s a tie!',
      'paper' => 'Player two wins!',
      'scissors' => 'Player one wins!',
    ),
    'paper' => array(
      'rock' => 'Player one wins!',
      'paper' => 'It\'s a tie!',
      'scissors' => 'Player two wins!',
    ),
    'scissors' => array(
      'rock' => 'Player two wins!',
      'paper' => 'Player one wins!',
      'scissors' => 'It\'s a tie!',
    ),
  );

  return '<p>' . $outcome[$one][$two] . '</p>';
}

function element_validate_rps($element) {
  $valid_entries = ['rock', 'paper', 'scissors'];
  $user_input = strtolower($element['#value']);
  if (!in_array($user_input, $valid_entries)) {
    form_error($element, t('That\'s not a valid entry. Please enter rock, paper, or scissors.'));
  }
}
